-- MySQL Script generated by MySQL Workbench
-- 11/04/14 22:10:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema compisDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `compisDB` ;

-- -----------------------------------------------------
-- Schema compisDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `compisDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `compisDB` ;

-- -----------------------------------------------------
-- Table `compisDB`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compisDB`.`usuario` ;

CREATE TABLE IF NOT EXISTS `compisDB`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compisDB`.`empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compisDB`.`empresa` ;

CREATE TABLE IF NOT EXISTS `compisDB`.`empresa` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `nit` VARCHAR(45) NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idempresa`),
  INDEX `fk_empresa_usuario_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_empresa_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `compisDB`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `compisDB`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compisDB`.`factura` ;

CREATE TABLE IF NOT EXISTS `compisDB`.`factura` (
  `idfacturacion` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL DEFAULT 'pendiente',
  `fecha_factura` DATE NOT NULL,
  `valor_factura` VARCHAR(45) NOT NULL,
  `num_factura` VARCHAR(45) NOT NULL,
  `empresa_idempresa` INT NOT NULL,
  PRIMARY KEY (`idfacturacion`, `empresa_idempresa`),
  INDEX `fk_facturacion_empresa1_idx` (`empresa_idempresa` ASC),
  CONSTRAINT `fk_facturacion_empresa1`
    FOREIGN KEY (`empresa_idempresa`)
    REFERENCES `compisDB`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compisDB`.`abono`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compisDB`.`abono` ;

CREATE TABLE IF NOT EXISTS `compisDB`.`abono` (
  `idabono` INT NOT NULL AUTO_INCREMENT,
  `fecha_pagada` DATE NOT NULL,
  `valor_pagado` VARCHAR(45) NOT NULL,
  `num_recibido` VARCHAR(45) NOT NULL,
  `factura_idfacturacion` INT NOT NULL,
  `factura_empresa_idempresa` INT NOT NULL,
  `observacion` VARCHAR(100) NULL,
  PRIMARY KEY (`idabono`),
  INDEX `fk_abono_factura1_idx` (`factura_idfacturacion` ASC, `factura_empresa_idempresa` ASC),
  CONSTRAINT `fk_abono_factura1`
    FOREIGN KEY (`factura_idfacturacion` , `factura_empresa_idempresa`)
    REFERENCES `compisDB`.`factura` (`idfacturacion` , `empresa_idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
